GET http://localhost:8080/characters
###

POST http://localhost:8080/characters
Content-Type: application/json

{
  "name": "Bergen"
}
###

GET http://localhost:8080/characters/1
###

PUT http://localhost:8080/characters/1
Content-Type: application/json

{
  "name": "Bergen Juanyshev"
}
###

DELETE http://localhost:8080/characters/1
###